# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ioport.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_c_shift_ram_0_0/design_1_c_shift_ram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_c_shift_ram_0_0 || ORIG_REF_NAME==design_1_c_shift_ram_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_c_shift_ram_0_2/design_1_c_shift_ram_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_c_shift_ram_0_2 || ORIG_REF_NAME==design_1_c_shift_ram_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_c_shift_ram_0_3/design_1_c_shift_ram_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_c_shift_ram_0_3 || ORIG_REF_NAME==design_1_c_shift_ram_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_reduced_logic_0_0/design_1_util_reduced_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_reduced_logic_0_0 || ORIG_REF_NAME==design_1_util_reduced_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_reduced_logic_0_1/design_1_util_reduced_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_reduced_logic_0_1 || ORIG_REF_NAME==design_1_util_reduced_logic_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_divider_8191_0_0/design_1_divider_8191_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_divider_8191_0_0 || ORIG_REF_NAME==design_1_divider_8191_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_0_0 || ORIG_REF_NAME==design_1_system_ila_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
