@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Jun 28 15:42:26 +0900 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim test_divider_p2_behav -key {Behavioral:sim_1:Functional:test_divider_p2} -tclbatch test_divider_p2.tcl -protoinst "protoinst_files/design_1.protoinst" -view D:/div_archive/div32p2check/test_divider_p2_behav.wcfg -log simulate.log"
call xsim  test_divider_p2_behav -key {Behavioral:sim_1:Functional:test_divider_p2} -tclbatch test_divider_p2.tcl -protoinst "protoinst_files/design_1.protoinst" -view D:/div_archive/div32p2check/test_divider_p2_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
